# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllImageIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainImg', models.ImageField(upload_to='images')),
                ('dashboardImg', models.ImageField(upload_to='images')),
                ('frontImg', models.ImageField(upload_to='images')),
                ('passFrontImg', models.ImageField(upload_to='images')),
                ('passRearImg', models.ImageField(upload_to='images')),
                ('rearImg', models.ImageField(upload_to='images')),
                ('driveRear', models.ImageField(upload_to='images')),
                ('driveFront', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='AllImageOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainImg', models.ImageField(upload_to='images')),
                ('dashboardImg', models.ImageField(upload_to='images')),
                ('frontImg', models.ImageField(upload_to='images')),
                ('passFrontImg', models.ImageField(upload_to='images')),
                ('passRearImg', models.ImageField(upload_to='images')),
                ('rearImg', models.ImageField(upload_to='images')),
                ('driveRear', models.ImageField(upload_to='images')),
                ('driveFront', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='DamageIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboardImg', models.BooleanField(default=False)),
                ('frontImg', models.BooleanField(default=False)),
                ('passFrontImg', models.BooleanField(default=False)),
                ('passRearImg', models.BooleanField(default=False)),
                ('rearImg', models.BooleanField(default=False)),
                ('driveRearImg', models.BooleanField(default=False)),
                ('driveFrontImg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MoreImageIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moreImage', models.ImageField(upload_to='images')),
                ('damage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MoreImageOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moreImage', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractNumber', models.CharField(blank=True, max_length=200)),
                ('plateNumber', models.CharField(blank=True, max_length=200)),
                ('dateOutTime', models.DateTimeField()),
                ('dateInTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('On Rent', 'On Rent'), ('Ready for review', 'Ready for review'), ('Pass', 'Pass'), ('Fail', 'Fail')], default='Ready for review', max_length=50)),
                ('damage', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='moreimageout',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moreImgOut', to='accounting.Post'),
        ),
        migrations.AddField(
            model_name='moreimagein',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moreImgIn', to='accounting.Post'),
        ),
        migrations.AddField(
            model_name='damagein',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='damgeOut', to='accounting.Post'),
        ),
        migrations.AddField(
            model_name='allimageout',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allImgOut', to='accounting.Post'),
        ),
        migrations.AddField(
            model_name='allimagein',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allImgIn', to='accounting.Post'),
        ),
    ]
