# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboardImg', models.ImageField(upload_to='images')),
                ('frontImg', models.ImageField(upload_to='images')),
                ('passFrontImg', models.ImageField(upload_to='images')),
                ('passRearImg', models.ImageField(upload_to='images')),
                ('rearImg', models.ImageField(upload_to='images')),
                ('driveRear', models.ImageField(upload_to='images')),
                ('driveFront', models.ImageField(upload_to='images')),
                ('moreImage', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractNumber', models.CharField(blank=True, max_length=200)),
                ('plateNumber', models.CharField(blank=True, max_length=200)),
                ('dateOutTime', models.DateTimeField()),
                ('dateInTime', models.DateTimeField()),
                ('status', models.CharField(choices=[('ALL', 'All'), ('ONRENT', 'On Rent'), ('REVIEW', 'Ready for review'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='REVIEW', max_length=50)),
                ('rentOut', models.BooleanField(default=False)),
                ('damage', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='allimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moreImg', to='accounting.Post'),
        ),
    ]
