# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitNumber', models.CharField(max_length=200)),
                ('plateNumber', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='cars')),
            ],
        ),
    ]
