# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreImageIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moreImage', models.ImageField(upload_to='images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moreImgIn', to='accounting.Post')),
            ],
        ),
        migrations.CreateModel(
            name='MoreImageOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moreImage', models.ImageField(upload_to='images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moreImgOut', to='accounting.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='allimagein',
            name='moreImage',
        ),
        migrations.RemoveField(
            model_name='allimageout',
            name='moreImage',
        ),
        migrations.AlterField(
            model_name='allimagein',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allImgIn', to='accounting.Post'),
        ),
        migrations.AlterField(
            model_name='allimageout',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allImgOut', to='accounting.Post'),
        ),
    ]
