# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-02 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170731_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='damgeOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboardImg', models.BooleanField(default=False)),
                ('frontImg', models.BooleanField(default=False)),
                ('passFrontImg', models.BooleanField(default=False)),
                ('passRearImg', models.BooleanField(default=False)),
                ('rearImg', models.BooleanField(default=False)),
                ('driveRearImg', models.BooleanField(default=False)),
                ('driveFrontImg', models.BooleanField(default=False)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='damgeOut', to='accounting.Post')),
            ],
        ),
    ]
