# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plateNumber',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='unitNumber',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
