# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170724_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rentOut',
        ),
        migrations.AlterField(
            model_name='post',
            name='dateInTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
