# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_damgeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreimagein',
            name='damage',
            field=models.BooleanField(default=False),
        ),
    ]
