# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20170724_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('On Rent', 'On Rent'), ('Ready for review', 'Ready for review'), ('Pass', 'Pass'), ('Fail', 'Fail')], default='Ready for review', max_length=50),
        ),
    ]
