# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20170724_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateInTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='dateOutTime',
            field=models.CharField(max_length=50),
        ),
    ]
