# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20170726_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateOutTime',
            field=models.DateTimeField(),
        ),
    ]
