# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'permissions': (('send_invitation', 'Can send invitation'),)},
        ),
    ]
